{{- range $i, $node := $.Values.targetNodes.nodes }}
{{- $hn := ($node.hostname | required (printf "node[%d]: hostname required" $i)) | lower | replace "_" "-" | replace "." "-" | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "xray-vpn.fullname" $ }}-{{ $hn }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ include "xray-vpn.fullname" $ }}-storageclass
---
{{- end }}