apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xray-vpn.fullname" $ }}-credentials
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
type: Opaque
stringData:
  PANEL_USER: {{ default "admin" (index $.Values.credentials "adminUsername") | quote }}
  PANEL_PASS: {{ default "admin" (index $.Values.credentials "adminPassword") | quote }}